// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"768","screenHeight":"432","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"logotip","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"MapHUD","status":true,"description":"Simple HUD plugin for thalesgal.","parameters":{"X":"0","Y":"0","Maps":"Luminaris,Aetheris,KristalnaAkademija,DvoranaMentorstva,Pansion,Taverna,Željezarija,Apoteka"}},
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"OrangeCustomEventCreator","status":true,"description":"This plugin Will let you create virtual events with script calls","parameters":{}},
{"name":"MMO_Core","status":true,"description":"MMORPG Maker MV - Core","parameters":{"Server Location":"http://127.0.0.1:8097/"}},
{"name":"MMO_Core_Player","status":true,"description":"MMORPG Maker MV - Core Handling Player","parameters":{"Mouse Movements":"true","Use Native Respawn":"false"}},
{"name":"MMO_Core_Players","status":true,"description":"MMORPG Maker MV - Core Handling Players","parameters":{}},
{"name":"MMO_Core_Party","status":true,"description":"MMORPG Maker MV - Core Handling Parties","parameters":{}},
{"name":"MMO_Core_Party_Combat","status":true,"description":"MMORPG Maker MV - Core Handling Combat in Party","parameters":{}},
{"name":"MMO_Core_Bank","status":true,"description":"MMORPG Maker MV - Core Handling Bank","parameters":{}},
{"name":"MMO_ChatBox","status":true,"description":"MMORPG Maker MV - ChatBox","parameters":{"chatPosition":"BOTTOM LEFT"}},
{"name":"MMO_LoginForm","status":true,"description":"MMORPG Maker MV - Login Form","parameters":{"allowAccountCreation":"Yes"}},
{"name":"MMO_Overhead","status":true,"description":"Add name over actors name","parameters":{}},
{"name":"MMO_iavra_event_popup","status":true,"description":"Allows to display popups messages above events, which can be used for speech bubbles or on chests.\r\n<Iavra Event Popup>","parameters":{"Popup Width":"200","Offset X":"0","Offset Y":"0","Display Duration":"200","Fade In Duration":"10","Fade Out Duration":"60","Font Name":"","Font Size":"12","Line Height":"18","Retain On Scene":"Scene_Menu, Scene_Battle\r"}},
{"name":"foi-agent-plugin","status":true,"description":"FOI Agent plugin (MMO version) - per-user server-side storage","parameters":{"FoiServerUrl":"http://localhost:5000"}},
{"name":"RS_InputDialog","status":true,"description":"This plugin allows you to display Text Edit Box on the screen. <RS_InputDialog>","parameters":{"textBox Width":"488","textBox Height":"36","variable ID":"3","debug":"false","Text Hint":"Please enter the value...","direction":"ltr","Max Length":"255","Style":"","CSS":"\"\"","Font Family":"GameFont","Button Name":"","Ok":"OK","Cancel":"Cancel","Position":"center"}},
{"name":"MStablemenu","status":false,"description":"Custom Menu Call","parameters":{"Menu Map ID":"11","Original Map ID Variable":"98","Original X Coordinate Variable":"99","Original Y Coordinate Variable":"100","Exit Common Event ID":"12","Disabled Menu Maps":"1,2,3,4,5,6,7,8,9,10"}}
];
